---
# Get count of ec2 with the given tag
- name: Get count of EC2
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - debug: var=manageiq.api_url
    - debug: var=manageiq.api_token
    - debug: var=manageiq.service
    - debug: var=manageiq.event_target
    - debug: var=manageiq.event_target
    - name: Remove the Purpose tag
      ec2_tag:
        region: us-east-1
        resource: i-08395f987fa07528b
        tags:
          Purpose:
        state: absent
