---
- name: Get attribute names in root object
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    - manageiq_validate_certs: false

  roles:
    - manageiq-core.manageiq-automate

  tasks:
    - name: "Get root object reference"
      manageiq_automate:
        workspace: "{{ workspace }}"
        get_object_attribute_names:
          object: "root"
      register: attribute_list

    - debug: msg="attribute_list is {{ attribute_list }}"
