---
# Get count of ec2 with the given tag
- name: Get count of EC2
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: Add a tag
      ec2:
        instance_tags:
          CountIs: One
