# Get count of ec2 with the given tag
- name: Encrypt S3 Bucket
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - debug: var=manageiq.api_token

    - name: Call Node-red api
      uri:
        url: https://localhost:1880/encrypts3
        method: POST
        body: '{ "name": "{{bucket_name}}"}'
        body_format: json
        status_code: 200
      register: response
    - debug: var=response
