# Create a new EC2 instance using terraform and after provisioning run a SSM command in it

- name: Terraform EC2 with SSM
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: Call Node-red api
      uri:
        url: http://localhost:1880/deploy-ec2-terraform
        method: POST
        # body: '{ "instanceId": "{{instanceId}}" , "username": "{{username}}"}'
        # body_format: json
        status_code: 200
      register: response
    - debug: var=response
