# Get count of ec2 with the given tag
- name: Call Terraform from ansible
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - debug: var="test_var"
    - debug: var="test_var"

    - name: Call Terraform api
      uri:
        url: http://21ab995c.ngrok.io/v1/terraformize_test/my_workspace2
        method: POST
        return_content: yes
        body: '{ "test_var": "{{ test_var }}" }'
        body_format: json
        status_code: 200
      register: response
    - debug: var=response
